djangoCVWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.IndexView.as_view(), name="home"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
    path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name='blog'),
    path('vr/', views.VRView.as_view(), name="vr"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from django_tex.core import compile_template_to_pdf
from cloudinary.models import CloudinaryField
from django.core.files.storage import FileSystemStorage
import os

# Create your models here.
file_storage = FileSystemStorage(location='media')

class Skill(models.Model):
    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = CloudinaryField(blank=True, null=True,)
    is_key_skill = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"

class UserProfile(models.Model):
    class Meta:
        verbose_name_plural = "User Profiles"
        verbose_name = "User Profile"

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = CloudinaryField(blank=True, null=True,)
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv", storage=file_storage)

    def __str__(self):
        return f'{self.user.first_name, self.user.last_name}'

class ContactProfile(models.Model):
    class Meta:
        verbose_name = "Contact Profile"
        verbose_name_plural = "Contact Profiles"
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name", max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'

class Testimonial(models.Model):
    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = CloudinaryField(blank=True, null=True,)
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"


class Media(models.Model):
    class Meta:
        verbose_name = "Media"
        verbose_name_plural = "Media Files"
        ordering = ["name"]

    image = CloudinaryField(blank=True, null=True,)
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class Portfolio(models.Model):
    class Meta:
        verbose_name = "Portfolio"
        verbose_name_plural = "Portfolio Profiles"
        ordering = ["name"]

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = CloudinaryField(blank=True, null=True,)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/portfolio/{self.slug}'

class Blog(models.Model):
    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blog Profiles"
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = CloudinaryField(blank=True, null=True,)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return f'/blog/{self.slug}'

class Certificate(models.Model):
    class Meta:
        verbose_name = 'Certificates'
        verbose_name_plural = 'Certificates'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

main/forms.py
from django import forms
from . models import ContactProfile


class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True,
                           widget=forms.TextInput(
                               attrs={
                                   'placeholder': '*Full name..',
                                   # 'class': 'form-control',
                               }
                           ))
    email = forms.EmailField(max_length=254, required=True,
                             widget=forms.TextInput(
                               attrs={
                                   'placeholder': '*Email..',
                                   # 'class': 'form-control',
                               }
                           ))

    message = forms.CharField(max_length=1000, required=True,
                              widget=forms.Textarea(
                               attrs={
                                   'placeholder': '*Message..',
                                   'rows': 6,
                                   # 'class': 'form-control',
                               }
                           ))
    class Meta:
        model = ContactProfile
        fields = ('name', 'email', 'message',)

main/views.py
from django.shortcuts import render
from django.contrib import messages
from . models import (UserProfile,
                      Blog,
                      Portfolio,
                      Testimonial,
                      Certificate,
                      )
# Create your views here.
from django.views import generic
from . forms import ContactForm

class IndexView(generic.TemplateView):
    template_name = "main/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        testimonials = Testimonial.objects.filter(is_active=True)
        certificates = Certificate.objects.filter(is_active=True)
        blogs = Blog.objects.filter(is_active=True)
        portfolio = Portfolio.objects.filter(is_active=True)

        context['testimonials'] = testimonials
        context['certificates'] = certificates
        context['blogs'] = blogs
        context['portfolio'] = portfolio
        return context

class VRView(generic.TemplateView):
    template_name = "main/vr.html"

class ContactView(generic.FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Thank you. We will be in touch soon!')
        return super().form_valid(form)

class PortfolioView(generic.ListView):
    model = Portfolio
    template_name = "main/portfolio.html"
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    template_name = "main/portfolio-detail.html"

class BlogView(generic.ListView):
    model = Blog
    template_name = "main/blog.html"
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)

class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = "main/blog-detail.html"

main/templates/main/partials/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->
<footer>
  <div class="footerCol">
    <div class="container">
      <ul class="socialCol">
        <li><a href="https://www.facebook.com/ivans.saponenko"><img src={% static 'images/fb.svg' %} alt="..."></a></li>
        <!--<li><a href="javascript:void(0)"><img src={% static 'images/insta.svg' %} alt="..."></a></li>-->
        <!--<li><a href="javascript:void(0)"><img src={% static 'images/twitter.svg' %} alt="..."></a></li>-->
        <li><a href="https://www.linkedin.com/in/ivanssaponenko/"><img src={% static 'images/linkedin.svg' %} alt="..."></a></li>
        <li><a href="https://github.com/ivansstyle/"><img src={% static 'images/github-mark.svg' %} alt="..."></a></li>
      </ul>
      <div class="copyrightCol">
        <p>Copyright ©{% now 'Y' %} All rights reserved. Designed by {{ me.first_name|title }}</p>
      </div>
    </div>
  </div>
</footer>
<!-- ================================
End Footer
================================= -->

main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}
            <script>
            alert("{{ message }}")
            </script>
        {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/partials/nav.html
{% load static %}
 <!-- ================================
Start Navigation Bar
================================= -->
<header>
  <div class="headerCol">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-auto">
          <div class="logoCol"><a href="{% url 'main:home' %}"><img src="{% static 'images/Logo_round.png' %}" alt="..."></a></div>
        </div>
        <div class="col">
          <div class="d-md-none">
            <button class="navToggle">
              <span class="navToggle__text">Toggle Menu</span>
            </button>
          </div>
          <div class="navCollapseCol">
            <div class="navCol">
              <ul>
                <li><a href="{% url 'main:home' %}">Home</a></li>
                <li><a href="{% url 'main:portfolios' %}">Portfolio</a></li>
                <li><a href="{% url 'main:blogs' %}">Blog</a></li>
                <li><a href="{% url 'main:contact' %}">Contact</a></li>
                  <li><a href="{% url 'main:vr' %}">VR Office</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- ================================
End Navigation Bar
================================= -->